export const productSeed = [
  // Herramientas
  { name: "Taladro Percutor Inalámbrico 18V", brand: "Bosch", category: "Herramientas", price: 89990, stock: 24, imageKey: "product-drill.jpg", description: "Taladro percutor profesional de 18V con batería de litio, ideal para trabajos pesados en madera, metal y concreto." },
  { name: "Martillo Carpintero 16oz", brand: "Stanley", category: "Herramientas", price: 12490, stock: 87, imageKey: "product-hammer.jpg", description: "Martillo de uña con mango de madera ergonómico, ideal para clavar y extraer clavos." },
  { name: "Esmeril Angular 4½\" 850W", brand: "Makita", category: "Herramientas", price: 49990, stock: 18, imageKey: "product-grinder.jpg", description: "Esmeril angular profesional para corte y desbaste, motor 850W, mango antivibración." },
  { name: "Sierra Circular 7¼\" 1400W", brand: "Bosch", category: "Herramientas", price: 79990, stock: 14, imageKey: "product-saw.jpg", description: "Sierra circular profesional con guía láser, ideal para cortes precisos en madera." },
  { name: "Atornillador Eléctrico 12V", brand: "Makita", category: "Herramientas", price: 39990, stock: 32, imageKey: "product-screwdriver-electric.jpg", description: "Atornillador inalámbrico compacto con torque ajustable y 2 baterías." },
  { name: "Caja de Herramientas 20 piezas", brand: "Stanley", category: "Herramientas", price: 24990, stock: 45, imageKey: "product-toolbox.jpg", description: "Set completo con destornilladores, llaves, alicates y martillo en estuche resistente." },
  { name: "Llave Inglesa Ajustable 12\"", brand: "Stanley", category: "Herramientas", price: 9990, stock: 73, imageKey: "product-wrench.jpg", description: "Llave inglesa cromada de alta resistencia, mordaza ajustable hasta 35mm." },
  { name: "Set Destornilladores 12pz", brand: "Bosch", category: "Herramientas", price: 14990, stock: 56, imageKey: "product-screwdriver-set.jpg", description: "Juego de destornilladores Phillips y planos con mango ergonómico antideslizante." },
  { name: "Pistola de Calor 2000W", brand: "Bosch", category: "Herramientas", price: 34990, stock: 22, imageKey: "product-heatgun.jpg", description: "Pistola de aire caliente con temperatura regulable de 50° a 600°C." },
  { name: "Taladro de Banco 350W", brand: "Makita", category: "Herramientas", price: 119990, stock: 8, imageKey: "product-bench-drill.jpg", description: "Taladro de columna con 5 velocidades, ideal para taller y trabajos de precisión." },
  { name: "Lijadora Orbital 240W", brand: "Bosch", category: "Herramientas", price: 44990, stock: 19, imageKey: "product-sander.jpg", description: "Lijadora orbital con sistema de aspiración y velocidad variable." },
  { name: "Llave de Tubo 14\"", brand: "Stanley", category: "Herramientas", price: 18990, stock: 41, imageKey: "product-pipewrench.jpg", description: "Llave Stillson de acero forjado para fontanería y trabajos pesados." },

  // Construcción
  { name: "Set de Tornillos Inox 200pz", brand: "Stanley", category: "Construcción", price: 7990, stock: 156, imageKey: "product-screws.jpg", description: "Surtido de tornillos y tuercas en acero inoxidable de distintas medidas." },
  { name: "Cemento Gris 25kg", brand: "Sika", category: "Construcción", price: 5990, stock: 200, imageKey: "product-cement.jpg", description: "Cemento de uso general para hormigones, morteros y estucos." },
  { name: "Saco de Arena Fina 25kg", brand: "FERREMAS", category: "Construcción", price: 2990, stock: 180, imageKey: "product-sand.jpg", description: "Arena seleccionada y tamizada para mezclas de mortero." },
  { name: "Ladrillo Fiscal (unidad)", brand: "FERREMAS", category: "Construcción", price: 390, stock: 1200, imageKey: "product-brick.jpg", description: "Ladrillo de arcilla cocida para muros estructurales y tabiques." },
  { name: "Plancha OSB 11mm 1.22x2.44m", brand: "FERREMAS", category: "Construcción", price: 18990, stock: 64, imageKey: "product-osb.jpg", description: "Tablero estructural de virutas orientadas para construcción y revestimiento." },
  { name: "Malla Acma C92 6x2.15m", brand: "FERREMAS", category: "Construcción", price: 22990, stock: 35, imageKey: "product-mesh.jpg", description: "Malla de acero electrosoldada para refuerzo de losas y radieres." },
  { name: "Clavo Punta París 3\" 1kg", brand: "Stanley", category: "Construcción", price: 3490, stock: 220, imageKey: "product-nails.jpg", description: "Clavo galvanizado para construcción y carpintería estructural." },
  { name: "Adhesivo de Construcción 600ml", brand: "Sika", category: "Construcción", price: 8990, stock: 78, imageKey: "product-adhesive.jpg", description: "Sellador adhesivo de poliuretano de alta resistencia para múltiples superficies." },
  { name: "Yeso 25kg", brand: "Sika", category: "Construcción", price: 4990, stock: 95, imageKey: "product-plaster.jpg", description: "Yeso para terminaciones interiores, fácil aplicación y rápido secado." },
  { name: "Cerámica Blanca 45x45 (caja)", brand: "FERREMAS", category: "Construcción", price: 14990, stock: 60, imageKey: "product-tile.jpg", description: "Cerámica esmaltada para piso y muro, rendimiento 1.62m² por caja." },

  // Pinturas
  { name: "Esmalte Sintético Blanco 1 Galón", brand: "Sika", category: "Pinturas", price: 18990, stock: 42, imageKey: "product-enamel.jpg", description: "Pintura esmalte de alta cobertura, acabado brillante, resistente a la intemperie." },
  { name: "Pintura Látex Interior 5 Gal", brand: "Sika", category: "Pinturas", price: 34990, stock: 21, imageKey: "product-latex-bucket.jpg", description: "Pintura látex lavable de alta cobertura para interiores, terminación mate." },
  { name: "Látex Exterior 1 Galón", brand: "Sika", category: "Pinturas", price: 22990, stock: 38, imageKey: "product-paint.jpg", description: "Pintura acrílica exterior con protección UV y antihongos." },
  { name: "Barniz Marino 1 Litro", brand: "Sika", category: "Pinturas", price: 12990, stock: 47, imageKey: "product-varnish.jpg", description: "Barniz transparente con filtro UV, resistente al agua y la sal." },
  { name: "Brocha Profesional 3\"", brand: "FERREMAS", category: "Pinturas", price: 4990, stock: 120, imageKey: "product-brush.jpg", description: "Brocha de cerda mixta con mango ergonómico, ideal para esmaltes y látex." },
  { name: "Rodillo Antigota 22cm", brand: "FERREMAS", category: "Pinturas", price: 5990, stock: 95, imageKey: "product-roller.jpg", description: "Rodillo profesional con cubierta antigota, incluye marco metálico." },
  { name: "Diluyente para Esmalte 1L", brand: "Sika", category: "Pinturas", price: 4490, stock: 80, imageKey: "product-thinner.jpg", description: "Diluyente sintético para limpieza de herramientas y dilución de esmaltes." },
  { name: "Pintura Anticorrosiva Roja 1Gal", brand: "Sika", category: "Pinturas", price: 19990, stock: 28, imageKey: "product-anticorrosive.jpg", description: "Esmalte base óxido para protección de superficies metálicas." },
  { name: "Sellador Acrílico Blanco 280ml", brand: "Sika", category: "Pinturas", price: 3990, stock: 140, imageKey: "product-sealant.jpg", description: "Sellador para grietas y juntas en muros, pintable y flexible." },
  { name: "Bandeja para Pintura Plástica", brand: "FERREMAS", category: "Pinturas", price: 2990, stock: 110, imageKey: "product-tray.jpg", description: "Bandeja resistente compatible con rodillos hasta 25cm." },
  { name: "Spray Multicolor 400ml", brand: "Sika", category: "Pinturas", price: 5490, stock: 160, imageKey: "product-spray.jpg", description: "Aerosol de secado rápido para múltiples superficies, varios colores disponibles." },

  // Eléctrico
  { name: "Cable Eléctrico THHN 2.5mm 25m", brand: "Bosch", category: "Eléctrico", price: 22490, stock: 38, imageKey: "product-cable.jpg", description: "Rollo de cable eléctrico THHN para instalaciones residenciales e industriales." },
  { name: "Cable Eléctrico THHN 4mm 100m", brand: "Bosch", category: "Eléctrico", price: 79990, stock: 14, imageKey: "product-cable.jpg", description: "Cable de cobre con aislación termoplástica, ideal para instalaciones fijas." },
  { name: "Interruptor Simple 9/12", brand: "FERREMAS", category: "Eléctrico", price: 1990, stock: 220, imageKey: "product-switch.jpg", description: "Interruptor de empotrar con placa blanca, 10A 250V." },
  { name: "Enchufe Doble Schuko", brand: "FERREMAS", category: "Eléctrico", price: 3490, stock: 180, imageKey: "product-outlet.jpg", description: "Enchufe doble con tierra de protección para instalaciones modernas." },
  { name: "Tablero Eléctrico 12 Polos", brand: "Bosch", category: "Eléctrico", price: 39990, stock: 22, imageKey: "product-panel.jpg", description: "Caja de distribución con riel DIN para automáticos y diferenciales." },
  { name: "Automático 16A Curva C", brand: "Bosch", category: "Eléctrico", price: 6990, stock: 95, imageKey: "product-breaker.jpg", description: "Interruptor automático monopolar para protección de circuitos." },
  { name: "Diferencial 2x40A 30mA", brand: "Bosch", category: "Eléctrico", price: 24990, stock: 41, imageKey: "product-rcd.jpg", description: "Protector diferencial bipolar contra fugas a tierra." },
  { name: "Foco LED 9W E27 (pack 4)", brand: "FERREMAS", category: "Eléctrico", price: 9990, stock: 130, imageKey: "product-bulb.jpg", description: "Pack de 4 ampolletas LED luz cálida, equivalente 60W incandescente." },
  { name: "Tubo LED 18W 1.20m", brand: "FERREMAS", category: "Eléctrico", price: 7990, stock: 88, imageKey: "product-ledtube.jpg", description: "Tubo LED T8 alta eficiencia, vida útil 30.000 horas." },
  { name: "Alargador 5m con 4 Tomas", brand: "FERREMAS", category: "Eléctrico", price: 8990, stock: 72, imageKey: "product-extension.jpg", description: "Extensión eléctrica con interruptor y protección contra sobrecargas." },
  { name: "Multiherramienta Detector", brand: "Bosch", category: "Eléctrico", price: 49990, stock: 16, imageKey: "product-detector.jpg", description: "Detector de cables, metales y vigas en muros con pantalla LCD." },

  // Seguridad
  { name: "Casco de Seguridad + Antiparras", brand: "FERREMAS", category: "Seguridad", price: 9490, stock: 65, imageKey: "product-helmet.jpg", description: "Kit de protección personal certificado, casco amarillo y antiparras claras." },
  { name: "Guantes de Cuero Reforzado", brand: "FERREMAS", category: "Seguridad", price: 4990, stock: 180, imageKey: "product-gloves.jpg", description: "Guantes de cuero vacuno con refuerzo en palma, talla universal." },
  { name: "Mascarilla N95 (pack 10)", brand: "FERREMAS", category: "Seguridad", price: 12990, stock: 90, imageKey: "product-mask.jpg", description: "Respirador con filtro 95% de partículas, certificación NIOSH." },
  { name: "Zapatos de Seguridad Punta de Acero", brand: "FERREMAS", category: "Seguridad", price: 39990, stock: 48, imageKey: "product-boots.jpg", description: "Calzado industrial con punta de acero y suela antideslizante." },
  { name: "Arnés de Seguridad 4 Argollas", brand: "FERREMAS", category: "Seguridad", price: 49990, stock: 22, imageKey: "product-harness.jpg", description: "Arnés de cuerpo completo para trabajos en altura, certificado." },
  { name: "Chaleco Reflectante Naranjo", brand: "FERREMAS", category: "Seguridad", price: 4490, stock: 200, imageKey: "product-vest.jpg", description: "Chaleco de alta visibilidad con cintas reflectantes 360°." },
  { name: "Tapones Auditivos (par)", brand: "FERREMAS", category: "Seguridad", price: 1990, stock: 350, imageKey: "product-earplugs.jpg", description: "Protectores auditivos de silicona reutilizables, atenuación 27dB." },
  { name: "Extintor PQS 6kg ABC", brand: "FERREMAS", category: "Seguridad", price: 29990, stock: 35, imageKey: "product-extinguisher.jpg", description: "Extintor polvo químico seco para fuegos clase A, B y C." },
  { name: "Lentes Oscuros Industriales", brand: "FERREMAS", category: "Seguridad", price: 5990, stock: 140, imageKey: "product-glasses.jpg", description: "Lentes de seguridad con protección UV para soldadura ligera." },
  { name: "Botiquín Primeros Auxilios", brand: "FERREMAS", category: "Seguridad", price: 14990, stock: 60, imageKey: "product-firstaid.jpg", description: "Botiquín completo para obras y oficinas, 50 elementos." },
];
