import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

type Language = "es" | "en" | "pt";

const labels = {
  // Aqui se guardan traducciones manuales para la interfaz principal.
  // Aca no se usa Google Translate porque una API externa agregaria credenciales,
  // costo y dependencia; para la demo basta con textos controlados.
  es: {
    home: "Inicio",
    catalog: "Catalogo",
    branches: "Sucursales",
    search: "Buscar productos, marcas, SKU...",
    searchShort: "Buscar...",
    signIn: "Ingresar",
    cart: "Carrito",
    profile: "Mi perfil",
    orders: "Mis compras",
    signOut: "Cerrar sesion",
    productNotFound: "Producto no encontrado",
    backToCatalog: "Volver al catalogo",
    back: "Volver",
    sku: "SKU",
    vatIncluded: "IVA incluido",
    referenceRate: "Referencia Banco Central",
    language: "Idioma",
    available: "unidades disponibles",
    outOfStock: "Sin stock",
    description: "Descripcion",
    addToCart: "Agregar al carrito",
    keepBrowsing: "Seguir explorando",
    shippingTitle: "Despacho a todo Chile",
    shippingText: "2 a 5 dias habiles",
    warrantyTitle: "Garantia oficial",
    warrantyText: "12 meses fabrica",
    pickupTitle: "Retiro en tienda",
    pickupText: "Gratis en 6 sucursales",
    finalPaymentClp: "El pago final se realiza en CLP.",
    since1985: "Distribuidora desde 1985",
    heroTitleA: "Todo para construir,",
    heroTitleB: "renovar y reparar.",
    heroCopy:
      "Herramientas, materiales electricos, pinturas y seguridad de las mejores marcas. Compra online con retiro en tienda o despacho a domicilio.",
    viewCatalog: "Ver catalogo",
    findStore: "Encuentra una sucursal",
    homeDelivery: "Despacho a domicilio",
    homeDeliveryText: "En la Region Metropolitana y regiones.",
    storePickup: "Retiro en tienda",
    storePickupText: "En cualquiera de nuestras 7 sucursales.",
    paymentMethods: "Multiples medios de pago",
    paymentMethodsText: "Debito, credito y transferencia.",
    trustedBrands: "Marcas confiables",
    trustedBrandsText: "Bosch, Makita, Stanley, Sika.",
    featuredCategories: "Categorias destacadas",
    featuredCategoriesText: "Encuentra rapidamente lo que necesitas.",
    featuredProducts: "Productos destacados",
    featuredProductsText: "Lo mas vendido esta semana.",
    viewAll: "Ver todo",
    professionalCtaTitle: "¿Eres profesional o constructora?",
    professionalCtaText:
      "Accede a precios mayoristas, despachos coordinados y atencion dedicada en cualquiera de nuestras sucursales.",
    contactUs: "Contactanos",
    categoryAll: "Todos",
    categoryTools: "Herramientas",
    categoryConstruction: "Construccion",
    categoryPaints: "Pinturas",
    categoryElectrical: "Electrico",
    categorySafety: "Seguridad",
    productsAvailable: "productos disponibles en linea",
    pages: "paginas",
    searchProductSkuBrand: "Buscar producto, SKU o marca...",
    noProductsFound: "No se encontraron productos.",
    showing: "Mostrando",
    of: "de",
    previous: "Anterior",
    next: "Siguiente",
    stock: "Stock",
    add: "Agregar",
    footerDescription:
      "Distribuidora de productos de ferreteria y construccion desde 1985. Calidad y servicio para profesionales y hogar.",
    store: "Tienda",
    company: "Empresa",
    ourBranches: "Nuestras sucursales",
    contact: "Contacto",
    academicDemo: "Integracion de Plataformas (ASY5131) - Demo academica",
    cartTitle: "Carrito de compras",
    cartSubtitle: "Revisa tu pedido y completa el proceso de compra.",
    securePurchase: "Compra segura",
    orderInHistory: "Tu pedido quedara disponible en tu historial de compras.",
    emptyCart: "Tu carrito esta vacio.",
    goToCatalog: "Ir al catalogo",
    contactData: "Datos de contacto",
    edit: "Editar",
    name: "Nombre",
    email: "Email",
    phone: "Telefono",
    rut: "RUT",
    delivery: "Entrega",
    homeShipping: "Despacho a domicilio",
    free: "Gratis",
    pickupBranch: "Sucursal de retiro",
    paymentMethod: "Metodo de pago",
    bankTransfer: "Transferencia bancaria",
    bankTransferText: "Registra el pedido y deja el pago pendiente de confirmacion manual.",
    webpayText: "Pago seguro con debito o credito en la pasarela oficial de Transbank.",
    secureWebpayNote:
      "Las tarjetas ya no se procesan dentro de esta app. El cobro se realiza en Webpay Plus para cumplir un flujo mas seguro y compatible con Transbank.",
    internationalPurchase: "Compra internacional",
    internationalPurchaseText: "Muestra una referencia en moneda extranjera usando Banco Central.",
    hide: "Ocultar",
    seeTotal: "Ver total",
    totalIn: "Quiero ver mi total en",
    consultingCentralBank: "Consultando Banco Central...",
    officialTotalToPay: "Total oficial a pagar",
    reference: "Referencia",
    centralBankDate: "Fecha BCCh",
    foreignCurrencyNote:
      "Webpay Plus procesa el pago en pesos chilenos. La moneda extranjera es solo una referencia.",
    summary: "Resumen",
    subtotal: "Subtotal",
    total: "Total",
    processing: "Procesando...",
    payWithTransbank: "Pagar con Transbank",
    confirmOrder: "Confirmar pedido",
    orderRegistered: "Pedido registrado",
    pendingManualPayment: "Tu pedido quedo pendiente de validacion manual del pago.",
    keepShopping: "Seguir comprando",
    seeMyOrders: "Ver mis compras",
    remove: "Eliminar",
    dispatchAddress: "Direccion de despacho",
    addAddress: "Agregar",
    missingAddress: "Aun no has registrado una direccion.",
    storePickupOption: "Retiro en tienda",
    webpayName: "Webpay Plus (Transbank)",
    cardsHandledByWebpay:
      "Las tarjetas ya no se procesan dentro de esta app. El cobro se realiza en Webpay Plus para cumplir un flujo mas seguro y compatible con Transbank.",
    toTransfer: "Datos para transferencia",
    transferInstructions:
      "Realiza la transferencia a la cuenta indicada y luego confirma para registrar tu pedido.",
    bank: "Banco",
    accountType: "Tipo de cuenta",
    accountNumber: "N de cuenta",
    businessName: "Razon social",
    amountToTransfer: "Monto a transferir",
    transferRutNote: "Importante: indica tu RUT en el comentario de la transferencia para identificar tu pago.",
    cancel: "Cancelar",
    transferDone: "Ya transferi, confirmar pedido",
    copied: "copiado",
    copyFailed: "No se pudo copiar",
  },
  en: {
    home: "Home",
    catalog: "Catalog",
    branches: "Stores",
    search: "Search products, brands, SKU...",
    searchShort: "Search...",
    signIn: "Sign in",
    cart: "Cart",
    profile: "My profile",
    orders: "My orders",
    signOut: "Sign out",
    productNotFound: "Product not found",
    backToCatalog: "Back to catalog",
    back: "Back",
    sku: "SKU",
    vatIncluded: "VAT included",
    referenceRate: "Central Bank reference",
    language: "Language",
    available: "units available",
    outOfStock: "Out of stock",
    description: "Description",
    addToCart: "Add to cart",
    keepBrowsing: "Keep browsing",
    shippingTitle: "Shipping across Chile",
    shippingText: "2 to 5 business days",
    warrantyTitle: "Official warranty",
    warrantyText: "12 months factory warranty",
    pickupTitle: "Store pickup",
    pickupText: "Free in 6 stores",
    finalPaymentClp: "Final payment is processed in CLP.",
    since1985: "Distributor since 1985",
    heroTitleA: "Everything to build,",
    heroTitleB: "renovate and repair.",
    heroCopy:
      "Tools, electrical materials, paints and safety products from trusted brands. Buy online with store pickup or home delivery.",
    viewCatalog: "View catalog",
    findStore: "Find a store",
    homeDelivery: "Home delivery",
    homeDeliveryText: "Available in the Metropolitan Region and other regions.",
    storePickup: "Store pickup",
    storePickupText: "Available at any of our 7 stores.",
    paymentMethods: "Multiple payment methods",
    paymentMethodsText: "Debit, credit and bank transfer.",
    trustedBrands: "Trusted brands",
    trustedBrandsText: "Bosch, Makita, Stanley, Sika.",
    featuredCategories: "Featured categories",
    featuredCategoriesText: "Quickly find what you need.",
    featuredProducts: "Featured products",
    featuredProductsText: "Best sellers this week.",
    viewAll: "View all",
    professionalCtaTitle: "Are you a professional or construction company?",
    professionalCtaText:
      "Access wholesale prices, coordinated deliveries and dedicated support at any of our stores.",
    contactUs: "Contact us",
    categoryAll: "All",
    categoryTools: "Tools",
    categoryConstruction: "Construction",
    categoryPaints: "Paints",
    categoryElectrical: "Electrical",
    categorySafety: "Safety",
    productsAvailable: "products available online",
    pages: "pages",
    searchProductSkuBrand: "Search product, SKU or brand...",
    noProductsFound: "No products found.",
    showing: "Showing",
    of: "of",
    previous: "Previous",
    next: "Next",
    stock: "Stock",
    add: "Add",
    footerDescription:
      "Hardware and construction products distributor since 1985. Quality and service for professionals and home projects.",
    store: "Store",
    company: "Company",
    ourBranches: "Our stores",
    contact: "Contact",
    academicDemo: "Platform Integration (ASY5131) - Academic demo",
    cartTitle: "Shopping cart",
    cartSubtitle: "Review your order and complete the purchase process.",
    securePurchase: "Secure purchase",
    orderInHistory: "Your order will be available in your purchase history.",
    emptyCart: "Your cart is empty.",
    goToCatalog: "Go to catalog",
    contactData: "Contact information",
    edit: "Edit",
    name: "Name",
    email: "Email",
    phone: "Phone",
    rut: "Chilean ID",
    delivery: "Delivery",
    homeShipping: "Home delivery",
    free: "Free",
    pickupBranch: "Pickup store",
    paymentMethod: "Payment method",
    bankTransfer: "Bank transfer",
    bankTransferText: "Register the order and leave payment pending for manual confirmation.",
    webpayText: "Secure debit or credit payment through Transbank's official gateway.",
    secureWebpayNote:
      "Cards are no longer processed inside this app. The charge is completed in Webpay Plus for a safer flow compatible with Transbank.",
    internationalPurchase: "International purchase",
    internationalPurchaseText: "Shows a foreign currency reference using the Central Bank.",
    hide: "Hide",
    seeTotal: "See total",
    totalIn: "I want to see my total in",
    consultingCentralBank: "Checking Central Bank...",
    officialTotalToPay: "Official total to pay",
    reference: "Reference",
    centralBankDate: "BCCh date",
    foreignCurrencyNote:
      "Webpay Plus processes payment in Chilean pesos. The foreign currency amount is only a reference.",
    summary: "Summary",
    subtotal: "Subtotal",
    total: "Total",
    processing: "Processing...",
    payWithTransbank: "Pay with Transbank",
    confirmOrder: "Confirm order",
    orderRegistered: "Order registered",
    pendingManualPayment: "Your order is pending manual payment validation.",
    keepShopping: "Keep shopping",
    seeMyOrders: "See my orders",
    remove: "Remove",
    dispatchAddress: "Shipping address",
    addAddress: "Add",
    missingAddress: "You have not registered an address yet.",
    storePickupOption: "Store pickup",
    webpayName: "Webpay Plus (Transbank)",
    cardsHandledByWebpay:
      "Cards are no longer processed inside this app. The charge is completed in Webpay Plus for a safer flow compatible with Transbank.",
    toTransfer: "Bank transfer details",
    transferInstructions:
      "Transfer the amount to the indicated account and then confirm to register your order.",
    bank: "Bank",
    accountType: "Account type",
    accountNumber: "Account number",
    businessName: "Business name",
    amountToTransfer: "Amount to transfer",
    transferRutNote: "Important: include your Chilean ID in the transfer comment so the payment can be identified.",
    cancel: "Cancel",
    transferDone: "I transferred, confirm order",
    copied: "copied",
    copyFailed: "Could not copy",
  },
  pt: {
    home: "Inicio",
    catalog: "Catalogo",
    branches: "Lojas",
    search: "Buscar produtos, marcas, SKU...",
    searchShort: "Buscar...",
    signIn: "Entrar",
    cart: "Carrinho",
    profile: "Meu perfil",
    orders: "Minhas compras",
    signOut: "Sair",
    productNotFound: "Produto nao encontrado",
    backToCatalog: "Voltar ao catalogo",
    back: "Voltar",
    sku: "SKU",
    vatIncluded: "IVA incluido",
    referenceRate: "Referencia Banco Central",
    language: "Idioma",
    available: "unidades disponiveis",
    outOfStock: "Sem estoque",
    description: "Descricao",
    addToCart: "Adicionar ao carrinho",
    keepBrowsing: "Continuar explorando",
    shippingTitle: "Entrega em todo o Chile",
    shippingText: "2 a 5 dias uteis",
    warrantyTitle: "Garantia oficial",
    warrantyText: "12 meses de fabrica",
    pickupTitle: "Retirada na loja",
    pickupText: "Gratis em 6 lojas",
    finalPaymentClp: "O pagamento final e processado em CLP.",
    since1985: "Distribuidora desde 1985",
    heroTitleA: "Tudo para construir,",
    heroTitleB: "renovar e reparar.",
    heroCopy:
      "Ferramentas, materiais eletricos, tintas e seguranca das melhores marcas. Compre online com retirada na loja ou entrega em domicilio.",
    viewCatalog: "Ver catalogo",
    findStore: "Encontrar uma loja",
    homeDelivery: "Entrega em domicilio",
    homeDeliveryText: "Na Regiao Metropolitana e regioes.",
    storePickup: "Retirada na loja",
    storePickupText: "Em qualquer uma das nossas 7 lojas.",
    paymentMethods: "Varios meios de pagamento",
    paymentMethodsText: "Debito, credito e transferencia.",
    trustedBrands: "Marcas confiaveis",
    trustedBrandsText: "Bosch, Makita, Stanley, Sika.",
    featuredCategories: "Categorias em destaque",
    featuredCategoriesText: "Encontre rapidamente o que voce precisa.",
    featuredProducts: "Produtos em destaque",
    featuredProductsText: "Mais vendidos desta semana.",
    viewAll: "Ver tudo",
    professionalCtaTitle: "Voce e profissional ou construtora?",
    professionalCtaText:
      "Acesse precos de atacado, entregas coordenadas e atendimento dedicado em qualquer uma das nossas lojas.",
    contactUs: "Fale conosco",
    categoryAll: "Todos",
    categoryTools: "Ferramentas",
    categoryConstruction: "Construcao",
    categoryPaints: "Tintas",
    categoryElectrical: "Eletrico",
    categorySafety: "Seguranca",
    productsAvailable: "produtos disponiveis online",
    pages: "paginas",
    searchProductSkuBrand: "Buscar produto, SKU ou marca...",
    noProductsFound: "Nenhum produto encontrado.",
    showing: "Mostrando",
    of: "de",
    previous: "Anterior",
    next: "Proximo",
    stock: "Estoque",
    add: "Adicionar",
    footerDescription:
      "Distribuidora de produtos de ferragem e construcao desde 1985. Qualidade e servico para profissionais e lar.",
    store: "Loja",
    company: "Empresa",
    ourBranches: "Nossas lojas",
    contact: "Contato",
    academicDemo: "Integracao de Plataformas (ASY5131) - Demo academica",
    cartTitle: "Carrinho de compras",
    cartSubtitle: "Revise seu pedido e conclua o processo de compra.",
    securePurchase: "Compra segura",
    orderInHistory: "Seu pedido ficara disponivel no historico de compras.",
    emptyCart: "Seu carrinho esta vazio.",
    goToCatalog: "Ir ao catalogo",
    contactData: "Dados de contato",
    edit: "Editar",
    name: "Nome",
    email: "Email",
    phone: "Telefone",
    rut: "Documento chileno",
    delivery: "Entrega",
    homeShipping: "Entrega em domicilio",
    free: "Gratis",
    pickupBranch: "Loja de retirada",
    paymentMethod: "Metodo de pagamento",
    bankTransfer: "Transferencia bancaria",
    bankTransferText: "Registra o pedido e deixa o pagamento pendente de confirmacao manual.",
    webpayText: "Pagamento seguro com debito ou credito na plataforma oficial da Transbank.",
    secureWebpayNote:
      "Os cartoes ja nao sao processados dentro desta app. A cobranca e realizada no Webpay Plus para um fluxo mais seguro e compativel com Transbank.",
    internationalPurchase: "Compra internacional",
    internationalPurchaseText: "Mostra uma referencia em moeda estrangeira usando o Banco Central.",
    hide: "Ocultar",
    seeTotal: "Ver total",
    totalIn: "Quero ver meu total em",
    consultingCentralBank: "Consultando Banco Central...",
    officialTotalToPay: "Total oficial a pagar",
    reference: "Referencia",
    centralBankDate: "Data BCCh",
    foreignCurrencyNote:
      "Webpay Plus processa o pagamento em pesos chilenos. A moeda estrangeira e apenas uma referencia.",
    summary: "Resumo",
    subtotal: "Subtotal",
    total: "Total",
    processing: "Processando...",
    payWithTransbank: "Pagar com Transbank",
    confirmOrder: "Confirmar pedido",
    orderRegistered: "Pedido registrado",
    pendingManualPayment: "Seu pedido esta pendente de validacao manual do pagamento.",
    keepShopping: "Continuar comprando",
    seeMyOrders: "Ver minhas compras",
    remove: "Remover",
    dispatchAddress: "Endereco de entrega",
    addAddress: "Adicionar",
    missingAddress: "Voce ainda nao cadastrou um endereco.",
    storePickupOption: "Retirada na loja",
    webpayName: "Webpay Plus (Transbank)",
    cardsHandledByWebpay:
      "Os cartoes ja nao sao processados dentro desta app. A cobranca e realizada no Webpay Plus para um fluxo mais seguro e compativel com Transbank.",
    toTransfer: "Dados para transferencia",
    transferInstructions:
      "Realize a transferencia para a conta indicada e depois confirme para registrar seu pedido.",
    bank: "Banco",
    accountType: "Tipo de conta",
    accountNumber: "Numero da conta",
    businessName: "Razao social",
    amountToTransfer: "Valor a transferir",
    transferRutNote: "Importante: indique seu documento chileno no comentario da transferencia para identificar o pagamento.",
    cancel: "Cancelar",
    transferDone: "Ja transferi, confirmar pedido",
    copied: "copiado",
    copyFailed: "Nao foi possivel copiar",
  },
};

type TranslationKey = keyof typeof labels.es;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // En esta parte se restaura el idioma elegido por el usuario.
    const saved = localStorage.getItem("ferremas_language");
    return saved === "en" || saved === "pt" ? saved : "es";
  });

  const setLanguage = (nextLanguage: Language) => {
    // Aqui se persiste el idioma para que sobreviva a recargas.
    localStorage.setItem("ferremas_language", nextLanguage);
    setLanguageState(nextLanguage);
  };

  useEffect(() => {
    // Aca se actualiza el atributo lang del documento para accesibilidad.
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: TranslationKey) => labels[language][key],
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage debe usarse dentro de LanguageProvider.");
  }
  return context;
};
